# Generated by Django 5.0 on 2023-12-08 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_alter_thing_name_alter_thing_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='created_at',
        ),
    ]
